# Generated by Django 2.2.2 on 2019-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190730_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Trello key'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='api_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Trello_secret'),
        ),
    ]
