# Generated by Django 2.2.2 on 2019-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190730_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Trello token'),
        ),
    ]
