# Generated by Django 2.2.2 on 2019-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190730_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Trello key'),
        ),
    ]
